### ISSUE TITLE
adding   google_maps_flutter: ^0.5.11 to my dependencies.

### ISSUE THREAD

**Issue by ItsNotMyFault** [googlecodelabs/google-maps-in-flutter#1]
if I had the following line : 
  google_maps_flutter: ^0.5.11
My App won't launch even if it wsa launching right before.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-base' has different version for the compile (15.0.1) and runtime (16.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by domesticmouse** [comment]
Per [google_maps_flutter pub package](https://pub.dev/packages/google_maps_flutter), the current version is 0.5.19. Can you confirm if that is the version in your `pubspec.lock`? If yes, please head directly over to [flutter/flutter issues](https://github.com/flutter/flutter/issues). Thanks!

**Comment by ItsNotMyFault** [comment]
the problem is that I was using google_maps_flutter (version didn't matter) but I was also trying to use location at the same time causing the above error.
