### ISSUE TITLE
AppDelegate.m  doesn't exist

### ISSUE THREAD

**Issue by HelloPb** [googlecodelabs/google-maps-in-flutter#10]
AppDelegate.m renamed to .swift file. So is the code lines referenced doesn't match either in Step 4 for ios platform

![image](https://user-images.githubusercontent.com/3183406/74602513-6df5e180-50fd-11ea-8ff8-da54b1664083.png)

**Comment by mybluedog24** [comment]
@HelloPb #5

**Comment by cmedamine** [comment]
i think they chenged .m to swift

**Comment by cmedamine** [comment]
**use this**
```
import UIKit
import Flutter
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("YOUR KEY HERE")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Comment by domesticmouse** [comment]
I've updated the [codelab](https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/#2) and this source repo to reflect Flutter 1.17. Please have a look and let me know if I've missed anything, thanks!
