### ISSUE TITLE
 Possible minor updates needed under Adding an API key for an iOS app

### ISSUE THREAD

**Issue by dev-aentgs** [googlecodelabs/google-maps-in-flutter#14]
The section under _**Adding an API key for an iOS app**_

> You also need to add a setting to ios/Runner/Info.plist. This entry forces Flutter on iOS into a single threaded mode, which is required for the platform view embedding to work. This technical restriction is being worked on and will be lifted before Google Maps moves out of Developer Preview.

 Mentions that 

> This technical restriction is being worked on and will be lifted before Google Maps moves out of Developer Preview.

Google Maps is out of developer preview right?

**Comment by domesticmouse** [comment]
Per https://pub.dev/packages/google_maps_flutter it's still Developer Preview.

**Comment by dev-aentgs** [comment]
Thank you @domesticmouse

**Comment by domesticmouse** [comment]
Thanks @dev-aentgs for your wide ranging review of our resources! Hopefully you have gained some insights from all your readings 😄
