### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by smrtsmrf** [googlecodelabs/google-maps-in-flutter#15]
I've followed the instructions 3-4 times, but I keep getting the same result. I even tried updating to the 0.5.31 version of the google maps plugin. I tried a different center point, but still no map. 

I get the same result on Android as well. Also cloning the code here and running it produces the same issue.

The widget seems to draw (see google logo and location icon at the bottom), but no actual map shows up. I'm at a loss.

![Screen Shot 2020-09-07 at 9 25 24 PM](https://user-images.githubusercontent.com/17756776/92429945-b552c680-f150-11ea-8f90-6d50662ef379.png)

**Comment by domesticmouse** [comment]
Given the google logo and the map controls are rendering, that means the google map widget is correctly inserted into the tree and rendering. Check the console log, I’m guessing it is complaining about missing an API key.

**Comment by smrtsmrf** [comment]
Running the app from VS Code, this is all I get in the console:

```
Google Maps SDK for iOS version: 3.9.0.0
New version of Google Maps SDK for iOS available: 3.10.0.0
```

However, if I use `flutter run`, this is what I get:

```
Google Maps SDK for iOS version: 3.9.0.0
New version of Google Maps SDK for iOS available: 3.10.0.0
Google Maps SDK for iOS cannot connect or validate APIKey: Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data={length = 145, bytes = 0x3c48544d 4c3e0a3c 48454144 3e0a3c54 ... 3c2f4854 4d4c3e0a }}
Your key may be invalid for your bundle ID: com.example.googleMaps
```

Thanks for the idea, I'll look into the issue with the API key. 

Though it'd be nice if that information was available when running from VS Code.

**Comment by Money1998** [comment]
you put this library in .yaml file (webview_flutter: ^0.3.19+9) so its work

**Comment by domesticmouse** [comment]
I've updated the [Adding Google Maps to a Flutter app](https://codelabs.developers.google.com/codelabs/google-maps-in-flutter) codelab that should cover most of the issues in this bug. 

@Money1998 I'm curious what you are using the webview for.
