### ISSUE TITLE
Section "Adding an API key for an iOS app" Needs update

### ISSUE THREAD

**Issue by subratamazumder** [googlecodelabs/google-maps-in-flutter#3]
New version of flatter app does not generate `ios/Runner/AppDelegate.m`, it's creating `AppDelegate.swift` file & instruction to update can be taken from [here](https://developers.google.com/maps/documentation/ios-sdk/get-api-key#add_key)

**Comment by ykws** [comment]
@subratamazumder Hi, #5 :)

**Comment by domesticmouse** [comment]
Updated the codelab for Flutter 1.17, which includes `AppDelegate.swift`.
