### ISSUE TITLE
Section "Set a declared platform for CocoaPods" also needs to get updated

### ISSUE THREAD

**Issue by oimos** [googlecodelabs/google-maps-in-flutter#4]
Cannot find the file – `ios/Podfile`, mentioned there.
I feel the tutorial seems to be outdated. I think they should update the tutorial itself.

**Comment by ykws** [comment]
@stoneshower Hi,

I guess that you said the following section.

https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/index.html?index=..%2F..index#4

We found the file - [ios/Podfile](https://github.com/googlecodelabs/google-maps-in-flutter/blob/master/step-4/ios/Podfile)

But `flutter run` has the warning.

```
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission
  rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for
  instructions.
To regenerate the Podfile, run:
  rm ios/Podfile
```

Then `rm ios/Podfile & flutter run`, regenerate the `ios/Podfile` and solved the warning :)

**Comment by domesticmouse** [comment]
The `ios/Podfile` should be auto-generated when you run the app with the `google_maps_flutter` plugin. The plugin depends on the `GoogleMaps` CocoaPods, so that dependency triggers the addition of CocoaPods to the iOS build.
