### ISSUE TITLE
Flutter 1.9 is updated with Swift

### ISSUE THREAD

**Issue by resten1497** [googlecodelabs/google-maps-in-flutter#5]
<img width="776" alt="스크린샷 2019-11-11 오후 2 28 59" src="https://user-images.githubusercontent.com/19689492/68563031-9b444b00-048f-11ea-8816-2dd120547322.png">

Flutter is updated with Swift, but the Codelab still consists of Objective-C
Can you add the swift code?

**Comment by ykws** [comment]
We got an example of Swift code based on generated by Flutter automatically.

```AppDelegate.swift
import UIKit
import Flutter

// Add the following import.
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

    // Add the following line, with your API key
    GMSServices.provideAPIKey("YOUR-API-KEY")

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Comment by george** [comment]
+1  Since `flutter create` defaults to `swift`, this could be a significant hurdle for the uninitiated. I'd be happy to write a PR if someone could point me in the right direction. That content doesn't seem to live in this repo.

**Comment by domesticmouse** [comment]
Updated the codelab to reflect Flutter 1.17. PTAL and let me know what you think.
