### ISSUE TITLE
Not all red squiggles are disappeared after generating locations.g.dart

### ISSUE THREAD

**Issue by bahriddin** [googlecodelabs/google-maps-in-flutter#6]
I followed as lesson shows but still, there are multiple errors:

![image](https://user-images.githubusercontent.com/3971918/69624797-72c86d80-1099-11ea-8f1c-02b5e0042269.png)

**Comment by domesticmouse** [comment]
That looks like either you didn't add `json_annotation` to your project's `pubspec.yaml`, or the tooling hasn't caught up to the updated `pubspec.yaml`. Restart the editor, maybe?
