### ISSUE TITLE
"Adding Google Maps to the app" needs details about enabling APIs

### ISSUE THREAD

**Issue by idimensionz** [googlecodelabs/google-maps-in-flutter#7]
Environment: AndroidStudio 3.5.2
Flutter doctor output:
```
[✓] Flutter (Channel master, v1.12.16-pre.35, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.16-pre.35 at /home/jmullen/Projects/idz/flutter
    • Framework revision b9a56b9f48 (3 days ago), 2019-11-29 20:40:44 -0500
    • Engine revision 8672e79af8
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jmullen/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/jmullen/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 7.0.1
    • GNU Make 4.2.1

[✓] Android Studio (version 3.5)
    • Android Studio at /home/jmullen/apps/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (5 available)
    • LG H931                   • LGH9315c0ae7c4 • android-arm64  • Android 9
      (API 28)
    • Android SDK built for x86 • emulator-5554  • android-x86    • Android 10
      (API 29) (emulator)
    • Linux                     • Linux          • linux-x64      • Linux
    • Chrome                    • chrome         • web-javascript • Google
      Chrome 78.0.3904.108
    • Web Server                • web-server     • web-javascript • Flutter
      Tools

• No issues found!
```

I created an API key for use on Android and added it to the manifest file. However I was seeing a message something like 'API not authorized' when I ran the app (via AndroidStudio) on my LG V30 phone. Also, the app ran but no map displayed. I eventually figured out that I needed to enable the "Maps SDK for Android" API in Google Cloud Platform. (IOS users probably need to enable the Maps SDK for iOS as well. It would be helpful to explicitly state this.

**Comment by domesticmouse** [comment]
It's the first paragraph on https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/index.html#3 under the title **It's all about the API keys**. What else should I add here?

**Comment by kadlugan** [comment]
@domesticmouse  First, Thanks for creating the tutorial! :) 

I had this same issue with the Google Map not displaying or crashing the app in iOS and Android emnulators.   I found the following [Flutter Map Issue Resolution](https://github.com/flutter/flutter/issues/30649#issuecomment-488100735) as noted by https://github.com/petrsvobodnikspider worked immediately as a fix.  You can see it gets a lot of likes and has helped many solve the issue.

I think a small highlight to ensure that the user has enabled both these in their Google Cloud Account would be a big help to new to flutter developers.  Thanks

![image](https://user-images.githubusercontent.com/4727614/107833773-6fc5b400-6de8-11eb-8020-4898b9010fe9.png)
