### ISSUE TITLE
Not found ios/Runner/AppDelegate.m file.

### ISSUE THREAD

**Issue by joshephan** [googlecodelabs/google-maps-in-flutter#9]
Unable to find file while writing code [following guide](https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/#3) document.
I created a new plutter project through the Android studio, and my Runner folder looks like this.
![제목 없음](https://user-images.githubusercontent.com/4365470/72204737-91a28800-34be-11ea-81e5-e1a0228509e8.jpg)

There are no AppDelegate.m and AppDelegate.h files, but only AppDelegate.swift file exist. How do I proceed with the guide in this case?

**Comment by joshephan** [comment]
I didn't see [former issue. ](https://github.com/googlecodelabs/google-maps-in-flutter/issues/3)

Edit AppDelegate.swift file to following code.

```
import UIKit
import Flutter
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("YOUR_API_KEY")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by yukon-pasindujayanath** [comment]
@joshephan 
Why did  you close this issue? Could you fix this?

**Comment by domesticmouse** [comment]
@yukon-pasindujayanath are you hitting the same issue? Around Flutter 1.17 we switched from generating Objective C files to Swift files by default. I've updated the codelab to take this reality into account.

However, it is time for me to update the codelab again, so I'm interested to understand what issues you are hitting.

**Comment by abhijeet-arya** [comment]
> I didn't see [former issue. ](https://github.com/googlecodelabs/google-maps-in-flutter/issues/3)
> 
> Edit AppDelegate.swift file to following code.
> 
> ```
> import UIKit
> import Flutter
> import GoogleMaps
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GMSServices.provideAPIKey("YOUR_API_KEY")
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```

Where is AppDelegate.swift file in flutter

**Comment by kkmurerwa** [comment]
Did you find the location of AppDelegate.swift in Flutter?

**Comment by aososam** [comment]
I found AppDelegate.swift in the folder ios/Runner but I still cannot find AppDelegate.m

**Comment by aacassandra** [comment]
why you closed this problem? @joshephan

**Comment by domesticmouse** [comment]
@aososam only one of `AppDelegate.swift` or `AppDelegate.m` is generated. You can choose which when you instantiate a project by selecting the default language for iOS, either Swift or Objective C. Any particular reason you want the Objective C version?
